language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install requests
  - pip install Gooey
  - pip install codecov
  - pip install pytest-cov
  
# command to run tests
script: 
  - py.test --cov=./
  - codecov
