language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  - pip install codecov
  - pip install pytest-cov
  
install:
  - pip install requests
  - pip install Gooey
  
# command to run tests
script: 
  - py.test

after_success:
  - codecov
  - py.test --cov=./
