theme: jekyll-theme-architect

title: [https://github.com/aroharia/GroupMe-Chat-Data-Analysis/blob/master/images/groupme_chat_data_analysis_logo.jpg]
description: [Get stats for any GroupMe chat!]

show_downloads: ["true"]
